name: GitHub Actions Hello test

on:
    schedule:
        - cron: '* * * * *'
jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Print Heello
              run: echo 'Hello'
            - name: Try to run proyect
              run: dotnet run
