name: Call API every 15 min

on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
            cd ./CursoBackendSln/CursoBackend
            ls ${{ github.workspace }}
            dotnet restore
    - name: Build
      run:  |
            cd ./CursoBackendSln/CursoBackend
            ls ${{ github.workspace }}
            dotnet build --no-restore 
    - name: Test
      run:  |
            cd ./CursoBackendSln/CursoBackend
            ls ${{ github.workspace }}
            dotnet test --no-build --verbosity normal 
    - name: Running CallAPI.cs
      run: dotnet run --project ./CursoBackendSln/ConsoleApp1

